id: P001700
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1923
  title: བདེ་གཤེགས་བསྟན་པའི་གསལ་བྱེད་ཆོས་ཀྱི་འབྱུང་གནས
  author: ''
  volumes:
    eabe1ea9c8c147a4acb69ebebd0edaeb:
      image_group_id: I5711
      title: ''
      volume_number: 1
      total_pages: 393
      base_file: v001.txt
